#+HUGO_BASE_DIR: ../../
#+TITLE: 我的 2018 年阅读总结
#+DATE: 2018-12-28
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: 阅读 总结 反思
#+HUGO_CATEGORIES: 阅读
#+HUGO_DRAFT: false
#+OPTIONS: author:nil

本文分两部分，前半部分是反思，后半部分是值得推荐的书。

回顾这一年读的书，依旧不多。老问题依旧存在：记录不够，输出太少。

有一些翻看过的书，由于没有记录，没有什么印象了。

英文书只读了两本，同样是老问题：太简单的书觉得没什么意思，有趣的书读起来又太费劲。提升英语能力是关键。

有些奇怪，今年都没怎么看计算机相关的书，回想起来，应该只是翻文档去了。


<!--more-->

* 反思：怎样阅读？

1. *带着目的阅读* 。试着问自己：我为什么要读这本书？这本书跟我有什么关系？
2. *抽样阅读，高效跳读* 。参见：[[https://www.yangzhiping.com/column/How-efficient-skip-read.html][怎样高效跳读 - 阳志平的网志]]
3. *至少输出一张卡片* 。可以是：
   - 一张反常识卡。
   - 回答跟我的关系。


将书分为三类：

1. 工具类： 不必刻意读，需要用时查找。
2. 消遣类： 只是消遣，没有特定目的。
3. 科学类： 带有目的性的阅读。

将书分为五个等级（参考 [[https://www.yangzhiping.com/psy/reading-2015.html][冷读热读：读书九问 - 阳志平的网志]] ）：

- 坏书： 作者没有诚意，纯粹为了虚名或稿费，此种书不必读。
- 可用的书： 书中内容有可取之处，速读即可。
- 力作： 有理，且能够带来启发，可以认真看看，并输出卡片。
- 杰作： 作者耗费了大量的心血，值得反复阅读，慢慢品味。
- 神作： 无需多言。

* 反思： 科学类书籍阅读步骤

1. 主题阅读，写下想要解决的问题、或者阅读目的。
2. 带着问题寻找相关书目，列成书单，收集至 zotero 新建的特定文件夹。
3. 找资源：下载电子书、购买实体书。
4. 粗略翻看书单中的每一本书。
5. 根据问题大小，书单大小，安排阅读计划，注意截止日期。
6. 与问题无关的内容一律一瞥而过。
7. 每本书至少输出一张卡片。
8. 将已读过的书在 zotero 中标记 tag 。
9. 根据主题，输出一篇文章，或者是一个总结。

* 在「安人书院」共读的几本书
** 《经验的疆界》 - 杰作
链接： [[https://book.douban.com/subject/6687032/][经验的疆界]] 。

关于探讨「经验」的一本书。篇幅不长，信息量却非常的大。值得重读。

给我最大的一个启发是：对于特定领域的技能（如编程、数学、英语），通过低智学习（试错、模仿、天择）来进行不断练习， *经验是非常重要的智慧源泉* 。比如，一个种地的农民，他即便不知道一粒种子发芽的机理是什么、施肥的原理是什么等等根本性问题，但这不妨碍他作为一个有经验的农民，种地要比那些植物研究人员要种的好。甚至说，在什么时节播种哪一种植物能够带来更大的收益，他也知道的更多。


** 《情报分析心理学》 - 力作
链接： [[https://book.douban.com/subject/26335793/][情报分析心理学]] 。 另一本翻译： [[https://book.douban.com/subject/26549446/][其实你不知道你错得离谱]] 。

面对大量的、矛盾的、真假难辨的信息，并且作为容易受「认知偏见」影响的人类，我们应该怎样做出合理的决策呢？书中给出了方法：利用「分析模型」，竞争性假设分析。

** 《七堂思维成长课》 - 力作
链接： [[https://book.douban.com/subject/30310710/][七堂思维成长课]] 。

哪七堂课？目标、效率、社交、决策、沟通、调节、精力。在这七个方面，书中给出了很多具体的行动方法。这是对每一个人都非常实用的一本书。

最大的启发：执行意图、防守模式。

** 《畅销的原理》 - 力作
链接： [[https://book.douban.com/subject/26919762/][畅销的原理]] 。

好的营销是怎样的？本书通过「最新的认知科学研究」提炼出的总结：

1. 使人熟悉
2. 社会认同
3. 做好最后一步
4. 给予用户亲身体验（禀赋效应）
5. 给予用户成就感
6. 默认选项就是你想要的结果
7. 提供一个用于比较的定锚
8. ……等等

** 《重塑大脑，重塑人生》 - 力作
链接： [[https://book.douban.com/subject/26296233/][重塑大脑，重塑人生]] 。

本性真的无法改变吗？本书着重介绍了「神经可塑性」。一个习惯，无论好坏，它都会在大脑中形成一条神经回路，并会在往后的实践中不断重复，从而变得难以改变。但是，难以改变 *不表示* 无法改变，通过不断重复新的习惯，形成并强化新的神经回路，可以弱化旧习惯的影响。

*「大脑地图」是动态的，每几个星期就改变一次。*

* 一些值得推荐的书
** 《战争与和平》 - 神作

链接： [[https://book.douban.com/subject/2253381/][战争与和平（全四册）]]。

其实还没有看完，惭愧，半年时间才看了三册。

《战争与和平》是我阅读的第二本托尔斯泰的书，第一本是《安娜卡列尼娜》。对托尔斯泰，一直都没特别的喜欢，主要原因无非是他书中的主要人物都是贵族。相比与他齐名的陀思妥耶夫斯基，写普通人物就多一些。不过这并不影响这本书在我心目中「神作」的地位。

历史，是少数领导者的意志决定的吗？托尔斯泰说，历史的进程包含着无数的偶然性，而这些偶然性又共同组成了历史的必然性。世界很大，也很复杂，一项决策之所以能够成功，是某种生活的睿智，以及一种顺应趋势的直觉。

#+BEGIN_QUOTE
“普弗尔是那些自信到不可救药、一成不变、宁愿殉道的人们中间的一个，这种人只能是德国人，因为只有德国人根据一种抽象观念——科学，也就是根据臆想的完美无缺的真理的知识，才有这样的自信。法国人之所以自信因为他认为他本人不论在智力还是在肉体，不论对男人还是对女人，都有一种不可抗拒的迷人力量。英国人很自信，其理由是他是世界上组织最完善的国家的公民，再者，一个英国人永远知道他应当做什么，而且知道他作为一个英国人所做的一切都毫无异议地正确。意大利人之所以自信，因为他总是激昂慷慨，容易忘掉自己和别人。 *俄国人自信是因为他什么都不知道，也不愿意知道，因为他不相信有什么东西是可以完全知道的。* ”
#+END_QUOTE

书中的两位主角：安德烈，对现实生活的矛盾与困惑；皮埃尔，对善与爱的探索。从他俩身上都看到了我自己某一部分的影子。

** 《僧侣与哲学家》 - 力作
链接： [[https://book.douban.com/subject/25978763/][僧侣与哲学家]] 。

本书是一对父子的对话。父亲，西方著名的哲学家。儿子，本是为极具潜力的生物学家，却在博士毕业后到尼泊尔的山区做了佛教僧侣。译者，赖声川，有名的话剧艺术家。

本书有意思的地方在于， *从西方传统哲学、近代科学，同佛学的对比，到关于智慧，关于生命意义的探索* 。

** 《何为良好生活》 - 杰作
链接： [[https://book.douban.com/subject/26363926/][何为良好生活]] 。

什么是善良？什么是快乐？什么是幸福？什么样的生活才是良好生活？知与行有怎样的关系？

这些问题，我们或许思考过，却又讲不清楚。陈嘉映先生用浅显、直白的话语来论述这些与我们的日常生活息息相关的议题。

感触最深的是「知行关系」一章：

#+BEGIN_QUOTE
你如果没见过慷慨大度的人事，你很难懂得慷慨大度是什么意思，这人有这人的大派，那人有那人的大派。

...

上文提到霍鲁曰关于静修实践的论述，他在那段话后接着说：在静修实践中，“我获得了一种经验，如何知道这个经验是否正确呢？当然最简单的途径就是去问问已经拥有丰富经验的人”。
#+END_QUOTE

#+BEGIN_QUOTE
初学者追随谁，本来难免偶然，他一开始也不大能够分辨优秀与流俗，梵高的画和一幅行画摆在那里，初学者把那幅行画当作典范。他无须认出真正的卓越，他只须认出长于自己的，模仿着这样做那样做。若这样做而不那样做是好的，是有道理的，慢慢地，他会明白其中的道理。上进一步之后，他的眼界就可能转变，认得出更卓越的东西，如此一步步进入一个传统。师傅领进门修行在个人，随着心智的生长，随着审美能力的生长，他后来不再把那幅行画而会把梵高当作典范。上文引用霍鲁日说要常常去问问已经拥有丰富经验的人，这个“问问”不是站在一个传统之外去打听什么，而是“彻底融入长老的经验和个性之中”。学习者总是根据自己的发展阶段和自己的领悟水平识认典范。他初学时的典范，后来虽被抛弃，却是达到更高标准的必要阶梯。德性方面的学习教化，跟审美方面的教化十分相似，我们的艺术“品味”如此生长，我们的人生“品味”也是这样生长起来的，并不需要多少理论指导。实践者融入榜样的经验和个性之中，培养起来的是phronesis，是洞察力，而不是理论知识。
#+END_QUOTE

这一章，陈嘉映先生为我指明了一种学习、实践的方法： *追随大师的脚步* 。比如我喜欢编程，那就向编程界的大牛学习，看他们的代码，学习他们解决问题的思路；我总喜欢胡思乱想，我想要平静我的内心，或许可以向佛教中的大师学习。

** 《易中天中华史》 - 力作
链接： [[https://book.douban.com/subject/25819260/][易中天中华史]] 。

写了一篇博文： [[https://www.xianmin.org/post/yizhongtian-chinese-history-1/][《易中天中华史》读后感（一）——身为中国人]]

奈何没有后续了。除了秦汉之前的内容令我比较有感触之外，从魏晋南北朝到隋唐，这整个民族大融合也令我感触颇深。只是不知该如何下笔。

北方游牧民族的血性，是一种魄力，一种勇往无前的力量。但是，光有力量不足以治理国家。治理国家，需要某种细腻的智慧，比如儒家的智慧。大唐，集力量与智慧，成就了一个伟大的国家，成就了盛世。

** 《战时笔记（1914-1917）》 - 力作
链接： [[https://book.douban.com/subject/24849817/][战时笔记（1914-1917）]]

写了一篇博文： [[https://www.xianmin.org/post/wartime-notes/][维特根斯坦的《战时笔记》]]

** 《今日简史》 - 可用之书
链接： [[https://book.douban.com/subject/30259720/][今日简史]] 。

没太多感想。不过，作者在最后一张谈到了「禅修」对他产生的好处，有点意思。

** 《Diary of a Wimpy Kid, Book 1》 - 可用之书

链接：  [[https://book.douban.com/subject/2375997/][Diary of a Wimpy Kid, Book 1]] 。

有趣的英文读物，适合闲暇的时候读一读。该作者出了好几本这个系列的书。

** 《英语魔法师之语法俱乐部》 - 杰作
链接： [[https://book.douban.com/subject/1014914/][英语魔法师之语法俱乐部]] 。

一本面向中国人的极好的英语语法书！目前还在读。

奶爸的评论： [[https://book.douban.com/review/5768463/][书读十遍方可深谙微言大义（英语魔法师之语法俱乐部）书评]]

** 《葛传椝向学习英语者讲话》 - 力作
链接： [[https://book.douban.com/subject/26286306/][葛传椝向学习英语者讲话]] 。

[[https://zh.wikipedia.org/wiki/%E8%91%9B%E5%82%B3%E6%A7%BC][葛传椝]] 老先生，中国外语教育界先驱之一，学习英语听一听他的建议，还是有帮助的。


** 《GitHub 入门与实践》 - 可用之书
链接： [[https://book.douban.com/subject/26462816/][GitHub入门与实践]] 。

可以通过这本书来了解 Github ，了解如何利用 git 来进行项目协作。

** 《Git 权威指南》 - 力作
链接： [[https://book.douban.com/subject/6526452/][Git权威指南]] 。

对 Git 的各个方面都有介绍，非常不错的教材。
