#+HUGO_BASE_DIR: ../
#+SEQ_TODO: TODO DRAFT DONE
#+PROPERTY: header-args :eval no


* 被遗弃的草稿

** TODO 在老家过年的一些感想
这个春节，我在老家过年，一方面和家人团聚，一方面给爷爷贺寿（我是长孙，这是我回家的主要原因）。我早早就结束了工作，早早回到了老家，在老家待了两周。一年到头，也就这两周跟家人在一起，和那么多的亲戚见面。尽管说我也曾在老家过了好几次年，但这些年在不同的地方过年有了不一样的经历，才发觉在老家过年有多么的不一样。有一些想法，不妨记录一下。


*** 传统秩序
我老家在福建的一个山村，也许是因为这个地方穷山恶水，至今还保留着不少传统习俗。比如，过年要祭灶、祭祖、祭天，要烧香拜佛、放鞭炮等等。

这些传统习俗，按照当代主流的观念，很多是要摒弃的。迷信，劳民伤财，污染环境。但我想谈谈它的正面意义，首要一点，就是汇聚家族宗亲的 *凝聚力* 。习俗只是象征意义上的一种仪式，基本上受过现代化熏陶的人都知道，那些是迷信，但为什么还那么做呢？这样的仪式，可以把大伙儿聚在一起。聚在一起做什么？交流交流近况，看看谁挣了钱了，有没有好的机会。现在的村里人，基本都在外地城市里，可能还在不同地方，难得过年回到家乡一聚。回家乡，就是因为这些传统还在。

村里有不少长辈在上世纪八九十年代就前往长江中下游一带的富饶地区经商，诞生了不少民营企业家。最初，他们都是拉上几个乡亲一起出去打拼。由于语言不通，福建人说话又带着浓厚的口音，在异乡生活着实不易。但因为传统的存在，又祭拜同一个祖先，他们非常的团结。比如，做生意需要拿货，拿货需要人脉和本钱，同乡人通常都会扶持同乡人一把，借给他一批货，卖完了再给钱，很多人当时就是这样挣到第一桶金的。除此之外，遇到困难会相互帮忙，挣到钱的人会把还在老家的人带出来一起挣钱。在我看来，这都是“传统的功劳”。


*** 传统的变化
近二十年，家乡发生了翻天覆地的变化（当然，整个中国都在巨变）。几百年了，一个平静的农村，原本都是土木结构的房子，现在竖起了一座座洋楼、水泥房。以前都要坐船过河的那个口岸修了一座桥，高铁高速也通了，水泥路直接修到了家门口。毫无疑问，大家的生活条件变好了。经济上的变化，也随之影响着传统的变化。


1. 对金钱的敬畏
2. 家庭观念的转变
3. 我们这一代人，对传统习俗已经不了解

*** 对金钱的敬畏
以前大家都没什么文化，读书人受尊敬，谁考取了功名就是整个家族的荣耀，村民们对知识多少还有些敬畏。现在不一样了，大家都念过书了，学历再高也没用，钱说了算，谁有钱谁就受尊敬。


*** 谁来干活？
帮爷爷干活儿，折纸钱，搞迷信用的。这个习俗我不了解存在了多久了，应该有很多年了，但是到了我父亲那一辈，基本都不会了。折纸钱是一件很乏味的事儿，数十张，对折，最后还要用不同的纸卷成一捆。我本意是不想做的，迷信，污染环境，有什么好做的呢？可毕竟帮爷爷干活儿，家里还是爷爷说了算，不好拒绝，坐下来慢慢折吧。心里想着正念，也许这是锻炼正念的机缘呢？后来还好，另外两个亲戚过来帮忙，两个小时也就完成了。否则还不知道要弄多久。


*** 关于亲戚

*** 如何改变

现如今，越来越多的人一到春节就出门旅游了，这可以通过旅游部门统计的每年春节期间不断增长的游客数量看出来。据我观察，这些游客绝大部分是现代化城市居民，他们的老家也许已经城市化了，也许老家的亲戚很久都没再联系了，在小区楼里过年也没多少年味，这么长的假期出门游玩岂不是更好？

* INBOX

** DONE JavaScript —— this 绑定                           :JavaScript:@计算机:
   CLOSED: [2017-11-14 Tue 14:39]
   :PROPERTIES:
   :EXPORT_FILE_NAME: javascript-this
   :END:

Google 搜索出来的两个不错的链接：

- [[https://jeffjade.com/2015/08/03/2015-08-03-javascript-this/][JavaScript 之 this 详解 | 晚晴幽草轩]]
- [[https://segmentfault.com/a/1190000003046071][JS 中 this 关键字详解 - JSer - SegmentFault]]


我是先阅读的 [[https://github.com/getify/You-Dont-Know-JS/blob/master/this%20&%20object%20prototypes/README.md#you-dont-know-js-this--object-prototypes][You-Dont-Know-JS: this & Object Prototypes]] 。再回过头看上面的那两篇文章，我觉得他们讲解的太复杂了，而 《You-Dont-Know-JS》 就归纳的非常好。

<!--more-->

以下是总结笔记：

JS 中的 =this= 总是指向一个对象 (Object)，这个对象是基于函数运行时 *动态绑定* 的。要判断 =this= 的绑定对象，首先找到这个函数的直接调用位置，然后应用下面四条规则来判断：

1. （new 绑定）由 =new= 调用？绑定到新创建的对象。
2. （强制绑定）由 =call= 或者 =apply= （或者 =bind= ）调用？绑定到指定的对象。
3. （隐式绑定）由上下文对象调用？绑定到那个上下文对象。
4. （默认绑定）在严格模式下绑定到 =undefined= ，否则绑定到全局对象。

例外，ES6 中的箭头函数会继承外层函数调用的 =this= 绑定。（和 ES6 之前代码中的 ~self = this~ 机制一样）

*** 默认绑定
#+BEGIN_SRC javascript
function foo() {
	console.log( this.a );
}

var a = 2;

foo(); // 输出 2
// 绑定到全局对象 a， 如果是严格模式，绑定到 undefined
#+END_SRC

*** 隐式绑定
#+BEGIN_SRC javascript
function foo() {
	console.log( this.a );
}

var obj = {
	a: 2,
	foo: foo
};

obj.foo(); // 输出 2
// 由对象 obj 调用，绑定到 obj
#+END_SRC

*** 注意：隐式绑定的丢失问题
#+BEGIN_SRC js
function foo() {
	console.log( this.a );
}

var obj = {
	a: 2,
	foo: foo
};

var bar = obj.foo; // 注意这个引用！

var a = "oops, global"; // 全局对象 a

bar(); // 输出： "oops, global" 绑定丢失！

setTimeout( obj.foo, 100 ); // 输出： "oops, global" 绑定丢失！
#+END_SRC

*** 强制绑定： apply, call, bind
#+BEGIN_SRC js
function foo() {
	console.log( this.a );
}

var obj = {
	a: 2
};

var bar = function() {
	foo.call( obj ); // 将 foo 的 this 强制绑定到对象 obj
};

bar(); // 输出：2
setTimeout( bar, 100 ); // 输出： 2

// 强制绑定的对象无法被覆盖
bar.call( window ); // 2
#+END_SRC

*** new 绑定
#+BEGIN_SRC js
function foo(a) {
	this.a = a;
}

var bar = new foo( 2 ); // 使用 new 绑定到对象 bar
console.log( bar.a ); // 输出 2
#+END_SRC


** TODO 博客写作流程之工具篇： emacs, orgmode & hugo               :@计算机:
:PROPERTIES:
:EXPORT_FILE_NAME: 00-emacs-orgmode-and-hugo-write-blog-flow
:END:

本文将对我个人的博文写作流程 *所用到的工具* 做一个总结与分享。从标题就可以看出来，主要有这几个工具： emacs, orgmode & hugo 。

如果没记错的话，我最早接触博客是在 2010 年从新浪博客开始的，后面几年辗转过好几个平台，但实际上没有写多少内容，那些有限的内容删的删、忘的忘，就好像没存在过一样。有时候，我自己也是很矛盾的人，有话想说，却又觉得没多少价值，有点儿担心自己是不是在制造信息垃圾呢？有时候，又有点儿虚荣心，希望自己写的东西，被人看见。可一旦那股热乎劲儿过去了，就不了了之了。但过了一段时间，又憋的难受，总想说点什么。

这几年，看着一个个平台的流行到衰微，看着有些人被封杀，或者不再发表内容，看着一个个独立博客关闭，或者转移到微信公众号，至于这背后真正发生了什么，我不了解。也许这个世界越来越急功近利了，越来越趋于娱乐化了？

我只是知道，我有话要说，有内容想分享，仅此而已。作为一个不是专业程序员，却又喜欢折腾代码的人，搭建一个属于自己的平台，只是小事一桩。这或许是对独立与自由的追求吧。

做点有趣、有料的事儿。
这几年，自己在做事、以及对待生活的心态上有了些许变化，也许是成熟了些吧。有些东西也不太在乎了


*** 博客生成工具： hugo

*** 博文写作工具： emacs + orgmode

*** 博文发布


** TODO 现代 JavaScript 开发流程简介

** DONE 维特根斯坦的《战时笔记》           :@阅读:note:维特根斯坦:哲学:思考:
   CLOSED: [2018-02-09 Fri 21:53]
   :PROPERTIES:
   :EXPORT_FILE_NAME: wartime-notes
   :END:
这本书是维特根斯坦在 1914年 至 1917年 一战期间当兵时所写的笔记。这份笔记包含两部分，一部分是私人日记，一部分是哲学笔记。他出身富贵人家，又有很高的学识，完全可以不去服兵役，但他还是去了，这是为什么？那年他 25 岁，与我的年龄相仿，我很好奇他的所思所想，并且窥探一个“天才”的私人日记会是一件很有趣的事儿。
   
<!--more-->

*** 又过得非常感性了，几乎每天都手淫
他在私人日记中经常提到的两件事，手淫和工作。今天又感性了，或者，直接点就是今天又手淫了，或者今天工作了多久。工作，指的是对逻辑问题的思考。他即便身在战场，每天听着炮火声，也在不断的思考学问。

也许是因为精神上的压力？而手淫则是放松的方式？不管怎么说，拥有高智商，也不一定就能够完全的自控。

他在部队里是孤独的，被排斥的。他在日记中不断提到，周围都是些愚蠢的野蛮人。在那样的环境下，他只能够给曾经的朋友写信交流思想。把托尔斯泰的一句话，”一个人从肉体上来说是软弱无力的，但是经由精神他成为自由的人“，当作内在的精神支柱。

*** 关于记录与思考
这三年间，他不断的在思考逻辑哲学的问题，并且做了大量的记录和笔记，这也成就了他之后创作出《逻辑哲学论》这本书。长时间保持热情、深入钻研，还有一点，大量的记录，没有一个天才是平白无故就能创作出杰作的，必定是投入了常人所不能投入的努力。如果非要说是天才的话，那我以为，就是他找到了他一生所要去追随的事业。

- 你有热衷的事业吗？
- 你有每天都为它思考、并且努力工作吗？
- 即便遇到挫折，你有反省吗？


** DONE 开源实践：写在 Jane 发布之后             :@杂文:Jane:Hugo:开源:练习:
   CLOSED: [2018-03-11 Sun 21:30]
   :PROPERTIES:
   :EXPORT_FILE_NAME: hugo-theme-jane-publish
   :END:

本周我发布了一个 [[https://gohugo.io/][Hugo]] 主题 [[https://github.com/xianmin/hugo-theme-jane][Jane]] ，Jane 克隆自 [[https://github.com/olOwOlo/hugo-theme-even][hugo-theme-even]] ，大体功能基本继承自 Even 。起先，我只是使用 Hugo 来发布博文，并且选择使用 Even 作为我的博客主题。后来觉得 Even 这个主题的样式我个人不是很喜欢，就自己动手改了。改动的地方多了，外观上基本上已经不是原来的 Even 了，就想着也许自己可以基于它单独创建一个主题，顺便练练手，于是就有了 Jane 这个项目。当我在四天前向 Hugo 官方提交这个主题之后，意外地获得了官方的肯定以及推荐[fn:1]。

<!--more-->

这是我第一次认真去做的开源项目。尽管说，5年多以前我就开始使用 git ，有了 github 账号，但从未提过一个 issue ，也未提交过一次 PR ，就像是一个在论坛长期潜水的人。英文写作能力不行、对迈开第一步有些许畏惧、没找到合适的切入点等等，这些都可以当作理由，而我跨出这一步，居然用了5年的时间。毫无疑问，这得感谢 Even 的作者，感谢开源世界。

在 Jane 被官方收录到主题仓库的第二天，就得到了几个 Star，并且收到了一位使用者的反馈[fn:2]，对于我这个项目维护者而言，无疑是一种无形的鼓励。如前文所说，Jane 最初只是按我个人的需求进行的改造。所改的内容，主要是增强读者的阅读体验，然后在此基础上，增强其它的一些功能，比如说标签页中的标签云、分类页更好的展示、多国语言支持等。由于我个人水平有限，也非专业的网站设计人员，它依然有很多可以改进的地方。如果看到这篇文章的你正巧也是 Jane 的使用者，欢迎给我提出宝贵的建议，或者像我一样自己动手修改。

这次实践对于我个人是一个好的开始。我开始使用 gitflow 来规范开发流程，开始规范自己的 commit 内容，开始认真对待文档，开始认真做一个项目。磨了几年的刀，终于开始砍柴了。


[fn:1] [[https://github.com/gohugoio/hugoThemes/issues/340][New Theme: Jane · Issue #340 · gohugoio/hugoThemes]]

[fn:2] [[https://github.com/xianmin/hugo-theme-jane/issues/1][Issue #1 · xianmin/hugo-theme-jane]]

* DONE 笔记：有关开源项目                                 :@计算机:开源:笔记:
  CLOSED: [2018-03-27 Tue 15:47]
  :PROPERTIES:
  :EXPORT_FILE_NAME: note-opensource-project
  :END:

以下内容是关于怎样参与到开源项目中的一些笔记，基本上摘自网络。


** 参考链接
 - [[https://www.phodal.com/blog/how-to-build-a-opensource-project/][开源之美：开源软件开发流程 - Phodal | Phodal - A Growth Engineer]]
 - [[https://juejin.im/post/59f98a196fb9a045132a03ed][零起点的开源社区贡献指南 - 掘金]]
 - [[http://www.ruanyifeng.com/blog/2016/01/commit_message_change_log.html][Commit message 和 Change log 编写指南 - 阮一峰的网络日志]]
 - [[https://www.git-tower.com/learn/git/ebook/cn/command-line/advanced-topics/git-flow][git-flow 的工作流程]]
 
<!--more-->

** 加入开源项目可以做的事儿
- 入门：翻译文档、报告 BUG
- 提 Issue
  - 报告 Bug 与提问
  - 提出并讨论新特性
  - 设定 Todo 目标
- 提 Pull Request
  - 修复 bug
  - 实现新特性
  - 优化性能
  - 例行更新（如文档、依赖版本等）

** 常用英文表达方式

*吐槽代码：*
- 表达 API 笨重不好用，可以说 =heavy to work with=
- 表达模块结构不好，可以说 =not intuitive=
- 表达处理方式太粗暴，可以说 =overkill=
- 表达逻辑可能有漏洞，可以说 =leaky=
- 表达要引入的东西太多，可以说 =aggressive=

*表达观点：*
- =I think= 有点儿武断
- 可以用 =In my (humble) opinion=
- 补充一个 =Not sure, maybe missing something=
- 用 =To my knowledge= 或者 =For me=

** commit 格式规范
#+BEGIN_SRC 
<type>(<scope>): <subject>
// 空一行
<body>
// 空一行
<footer>
#+END_SRC

*第一部分为 HEADER ：*

- =<type>= 说明 commit 的类别：
  - feat：新功能（feature）
  - fix：修补bug
  - docs：文档（documentation）
  - style： 格式（不影响代码运行的变动）
  - refactor：重构（即不是新增功能，也不是修改bug的代码变动）
  - test：增加测试
  - chore：构建过程或辅助工具的变动
- =<scope>= 说明 commit 影响的范围
- =<subject>= 是 commit 目的的简短描述，可加入 Issue 的编号如 =#11=

*第二部分为 Body ：*
Body 部分是对本次 commit 的详细描述，可以分成多行。下面是一个范例。

*最后部分为 Footer：*
1. 不兼容变动。以 =BREAKING CHANGE= 开头，后面是对变动的描述、以及变动理由和迁移方法。
2. 关闭 Issue。如， =Closes #123, #245, #992= ，一次性关闭多个 issue。

*特殊情况 Revert ：*

如果当前 commit 用于撤销以前的 commit，则必须以 =revert:= 开头，后面跟着被撤销 Commit 的 Header。

** 生成 CHANGE LOG
[[https://github.com/conventional-changelog/conventional-changelog][conventional-changelog/conventional-changelog: Generate a changelog from git metadata.]]

按照规范编写 commit 最大的好处就是自动化生成 Change Log 。


** git-flow 工作流程
[[https://github.com/petervanderdoes/gitflow-avh][petervanderdoes/gitflow-avh: AVH Edition of the git extensions to provide high-level repository operations for Vincent Driessen's branching model]]


