
* TODO 在老家过年的一些感想
这个春节，我在老家过年，一方面和家人团聚，一方面给爷爷贺寿（我是长孙，这是我回家的主要原因）。我早早就结束了工作，早早回到了老家，在老家待了两周。一年到头，也就这两周跟家人在一起，和那么多的亲戚见面。尽管说我也曾在老家过了好几次年，但这些年在不同的地方过年有了不一样的经历，才发觉在老家过年有多么的不一样。有一些想法，不妨记录一下。


** 传统秩序
我老家在福建的一个山村，也许是因为这个地方穷山恶水，至今还保留着不少传统习俗。比如，过年要祭灶、祭祖、祭天，要烧香拜佛、放鞭炮等等。

这些传统习俗，按照当代主流的观念，很多是要摒弃的。迷信，劳民伤财，污染环境。但我想谈谈它的正面意义，首要一点，就是汇聚家族宗亲的 *凝聚力* 。习俗只是象征意义上的一种仪式，基本上受过现代化熏陶的人都知道，那些是迷信，但为什么还那么做呢？这样的仪式，可以把大伙儿聚在一起。聚在一起做什么？交流交流近况，看看谁挣了钱了，有没有好的机会。现在的村里人，基本都在外地城市里，可能还在不同地方，难得过年回到家乡一聚。回家乡，就是因为这些传统还在。

村里有不少长辈在上世纪八九十年代就前往长江中下游一带的富饶地区经商，诞生了不少民营企业家。最初，他们都是拉上几个乡亲一起出去打拼。由于语言不通，福建人说话又带着浓厚的口音，在异乡生活着实不易。但因为传统的存在，又祭拜同一个祖先，他们非常的团结。比如，做生意需要拿货，拿货需要人脉和本钱，同乡人通常都会扶持同乡人一把，借给他一批货，卖完了再给钱，很多人当时就是这样挣到第一桶金的。除此之外，遇到困难会相互帮忙，挣到钱的人会把还在老家的人带出来一起挣钱。在我看来，这都是“传统的功劳”。


** 传统的变化
近二十年，家乡发生了翻天覆地的变化（当然，整个中国都在巨变）。几百年了，一个平静的农村，原本都是土木结构的房子，现在竖起了一座座洋楼、水泥房。以前都要坐船过河的那个口岸修了一座桥，高铁高速也通了，水泥路直接修到了家门口。毫无疑问，大家的生活条件变好了。经济上的变化，也随之影响着传统的变化。


1. 对金钱的敬畏
2. 家庭观念的转变
3. 我们这一代人，对传统习俗已经不了解

** 对金钱的敬畏
以前大家都没什么文化，读书人受尊敬，谁考取了功名就是整个家族的荣耀，村民们对知识多少还有些敬畏。现在不一样了，大家都念过书了，学历再高也没用，钱说了算，谁有钱谁就受尊敬。


** 谁来干活？
帮爷爷干活儿，折纸钱，搞迷信用的。这个习俗我不了解存在了多久了，应该有很多年了，但是到了我父亲那一辈，基本都不会了。折纸钱是一件很乏味的事儿，数十张，对折，最后还要用不同的纸卷成一捆。我本意是不想做的，迷信，污染环境，有什么好做的呢？可毕竟帮爷爷干活儿，家里还是爷爷说了算，不好拒绝，坐下来慢慢折吧。心里想着正念，也许这是锻炼正念的机缘呢？后来还好，另外两个亲戚过来帮忙，两个小时也就完成了。否则还不知道要弄多久。


** 关于亲戚

** 如何改变

现如今，越来越多的人一到春节就出门旅游了，这可以通过旅游部门统计的每年春节期间不断增长的游客数量看出来。据我观察，这些游客绝大部分是现代化城市居民，他们的老家也许已经城市化了，也许老家的亲戚很久都没再联系了，在小区楼里过年也没多少年味，这么长的假期出门游玩岂不是更好？
