
* INBOX

** WAITING 现代 JavaScript 开发流程简介

** 好玩的 HUGO

** 好玩的 EMACS

** 好玩的 orgmode

** 好玩的 Deepin Linux

** TODO 坚守开放的互联网

我写此篇文章的缘由，是最近读了霍炬先生的一篇文章—— [[http://www.ifanr.com/1005291][Facebook、隐私、监听广告以及我们如何失去自由的互联网的 | 爱范儿]] ——之后的感想。他去年还写过一篇表达了类似观点的文章——[[http://www.ifanr.com/885225][互联网完蛋了，已经。 | 爱范儿]] 。这两篇文章，他都是在他个人的微信公众号上发布的，而两个链接则是 =爱范儿= 转载的，是我根据文章标题用 Google 搜出的第一个结果。的确，如他所言，微信公众号是封闭的，是一座信息孤岛，对搜索引擎不友好，我也懒的去找原文链接了。

霍炬先生的 [[http://blog.devep.net/virushuo/][个人博客]] 从2014年1月21日之后就停止了更新，此后他写的文章基本都发表在微信公众号上，这实在是很遗憾的事。我曾经关注过的很多博客有不少都很久没有更新了，有的甚至网站都已经无法打开，当然也有像霍炬先生一样转移阵地到微信公众号的。这都是博主的个人选择，没什么好说的。我这篇文章主要想谈一谈我们为什么需要开放的互联网，为什么要坚守这个阵地，为什么互联网没有死


我对他不太熟悉，也忘了是什么时候开始关注他、订阅他的博客的。

*** 微信公众号的弊端

*** 个人站点的优势

*** 主动与被动的读者

*** 互联网越来越封闭了吗

有一天，你搜索一条内容，发现一条非常有价值的文章，而这篇文章居然是10年前就已经存在了的。
分享在开放互联网上的内容，即便时隔多年，它依然会被检索到

- 维护一个有效链接的重要性。服务器并不重要，重要的是要长期维护一个域名。
- 备份你的文章

还有什么作用呢？

想要表达、交流的冲动。

*** 从个人站点开始

*** 独立博客的价值

*** INOREADER

* 暂时搁置

** TODO 在老家过年的一些感想
 这个春节，我在老家过年，一方面和家人团聚，一方面给爷爷贺寿（我是长孙，这是我回家的主要原因）。我早早就结束了工作，早早回到了老家，在老家待了两周。一年到头，也就这两周跟家人在一起，和那么多的亲戚见面。尽管说我也曾在老家过了好几次年，但这些年在不同的地方过年有了不一样的经历，才发觉在老家过年有多么的不一样。有一些想法，不妨记录一下。


*** 传统秩序
 我老家在福建的一个山村，也许是因为这个地方穷山恶水，至今还保留着不少传统习俗。比如，过年要祭灶、祭祖、祭天，要烧香拜佛、放鞭炮等等。

 这些传统习俗，按照当代主流的观念，很多是要摒弃的。迷信，劳民伤财，污染环境。但我想谈谈它的正面意义，首要一点，就是汇聚家族宗亲的 *凝聚力* 。习俗只是象征意义上的一种仪式，基本上受过现代化熏陶的人都知道，那些是迷信，但为什么还那么做呢？这样的仪式，可以把大伙儿聚在一起。聚在一起做什么？交流交流近况，看看谁挣了钱了，有没有好的机会。现在的村里人，基本都在外地城市里，可能还在不同地方，难得过年回到家乡一聚。回家乡，就是因为这些传统还在。

 村里有不少长辈在上世纪八九十年代就前往长江中下游一带的富饶地区经商，诞生了不少民营企业家。最初，他们都是拉上几个乡亲一起出去打拼。由于语言不通，福建人说话又带着浓厚的口音，在异乡生活着实不易。但因为传统的存在，又祭拜同一个祖先，他们非常的团结。比如，做生意需要拿货，拿货需要人脉和本钱，同乡人通常都会扶持同乡人一把，借给他一批货，卖完了再给钱，很多人当时就是这样挣到第一桶金的。除此之外，遇到困难会相互帮忙，挣到钱的人会把还在老家的人带出来一起挣钱。在我看来，这都是「传统的功劳」。


*** 传统的变化
 近二十年，家乡发生了翻天覆地的变化（当然，整个中国都在巨变）。几百年了，一个平静的农村，原本都是土木结构的房子，现在竖起了一座座洋楼、水泥房。以前都要坐船过河的那个口岸修了一座桥，高铁高速也通了，水泥路直接修到了家门口。毫无疑问，大家的生活条件变好了。经济上的变化，也随之影响着传统的变化。


 1. 对金钱的敬畏
 2. 家庭观念的转变
 3. 我们这一代人，对传统习俗已经不了解

*** 对金钱的敬畏
 以前大家都没什么文化，读书人受尊敬，谁考取了功名就是整个家族的荣耀，村民们对知识多少还有些敬畏。现在不一样了，大家都念过书了，学历再高也没用，钱说了算，谁有钱谁就受尊敬。


*** 谁来干活？
 帮爷爷干活儿，折纸钱，搞迷信用的。这个习俗我不了解存在了多久了，应该有很多年了，但是到了我父亲那一辈，基本都不会了。折纸钱是一件很乏味的事儿，数十张，对折，最后还要用不同的纸卷成一捆。我本意是不想做的，迷信，污染环境，有什么好做的呢？可毕竟帮爷爷干活儿，家里还是爷爷说了算，不好拒绝，坐下来慢慢折吧。心里想着正念，也许这是锻炼正念的机缘呢？后来还好，另外两个亲戚过来帮忙，两个小时也就完成了。否则还不知道要弄多久。


*** 关于亲戚

*** 如何改变

 现如今，越来越多的人一到春节就出门旅游了，这可以通过旅游部门统计的每年春节期间不断增长的游客数量看出来。据我观察，这些游客绝大部分是现代化城市居民，他们的老家也许已经城市化了，也许老家的亲戚很久都没再联系了，在小区楼里过年也没多少年味，这么长的假期出门游玩岂不是更好？



* 《易中天中华史》

** 《易中天中华史》读后感（一）——身为中国人
*** 前言
#+BEGIN_QUOTE
凡读本书请先具下列诸信念： 
　　 
一、当信任何一国之国民，尤其是自称知识在水平线以上之国民，对其本国已往历史，应该略有所知。

　　（否则最多只算一有知识的人，不能算一有知识的国民。）
　　 
二、所谓对其本国已往历史略有所知者，尤必附随一种对其本国已往历史之温情与敬意。 

　　（否则只算知道了一些外国史，不得云对本国史有知识。）
　　 
三、所谓对其本国已往历史有一种温情与敬意者，至少不会对其本国已往历史抱一种偏激的虚无主义，
　　 
　　（即视本国已往历史为无一点有价值，亦无一处足以使彼满意。）
　　 
　　亦至少不会感到现在我们是站在已往历史最高之顶点， 
　　 
　　（此乃一种浅薄狂妄的进化观。）
　　 
　　而将我们当身种种罪恶与弱点，一切诿卸于古人。 
　　 
　　（此乃一种似是而非之文化自谴。）
　　 
四、当信每一国家必待其国民具备上列诸条件者比较渐多，其国家乃再有向前发展之希望。 
　　 
　　（否则其所改进，等于一个被征服国或次殖民地之改进，对其国家自身不发生关系。换言之，此种改进，无异是一种变相的文化征服，乃其文化自身之萎缩与消灭，并非其文化自身之转变与发皇。）

——钱穆《国史大纲》序言
#+END_QUOTE

以上是钱穆先生在《国史大纲》中所写的序言，同时也是我读史、对待本国已往历史的态度。自然而然，也是我阅读这本书《易中天中华史》的态度。

什么是中华文明？它是怎样形成的？它和其他文明有哪些区别，又有哪些共同的价值？它还有哪些独特的地方？它需要向其他文明借鉴什么？

这篇读后感是我读完《易中天中华史——第一部：先秦》之后的些许感想。

#+BEGIN_QUOTE
我写「中华史」，是要审视「世界文明中的中华文明」，找到「中华文明中的共同价值」，最终回答「我们是谁，从哪里来，到哪里去」这三大问题。
——卷二《国家》后记 巡航日志
#+END_QUOTE

*** 本书的特点

1. 行文通俗易懂；
2. 不仅仅只讲中华史，还讲与其他主流文明的对比；
3. 论点和推测有根据、有出处；
4. 不少令人耳目一新的观点。

这是一部既可当作消遣又能引人深思的普及历史的著作。

*** 天下主义者
在第一部中，一个有意思的观点是：中国人是「天下主义者」。

#+BEGIN_QUOTE
古人所谓「中国」，首先不是政治概念，而是文化概念，意思是「世界文化中心」。这个中心的地理条件是要在中原，因为这是古人心目中的「天下之中」。

——卷二 《国家》，第六章，闯他一回红灯，谁代表中国
#+END_QUOTE

与其他文明比较，我们民族为什么没有宗教？易中天先生认为，因为中国人是「天下主义者」。在天下主义者看来，国家不过是天下的一分子，就像大家族中的小家庭。因此，真正的人，只属于天下，不属于国家。

至少我们的祖先是这样。那些先贤「以天下为己任」，探索真理，探讨人性，探寻人生的真谛，追求更美好的社会，寻找解救世界的药方。尽管在历史的发展进程中，中华文明经历了数次分裂统一、改朝换代、外族入侵，管理制度的变革，外来文化的冲击，同时也打压不同的声音，但是，中华文明的精神内核一直延续了下来。

什么样的精神内核？

以人为本。「以祖宗代上帝，以圣人代神祇，以道德代法治，以纲常代信仰」。不信神，不信教。因此反而更开放更包容，容得下各种宗教、各种信仰、各种不同的价值观。

*** 以人为本
「以人为本」的思想是怎样产生的？

这得追溯到「周」。周从殷商手中接过了武林盟主的地位，殷商垮台的原因是「不把人当人」。在殷商时期，祭祀用「人牲」，陪葬用「人殉」，把人当器物，自然不得人心。胜利了的周，为了笼络人心，必须「把人当人」。这也就产生了最初的「以人为本」的思想。中华文明在这方面是非常「早熟」的。

从「以人为本」出发，到「以德治国」，到「以礼维持秩序，以乐保证和谐」，这是中华文明得以一直延续的解读密码。

*** 我的疑问
「以人为本」的准确标准是什么？

*** 本书与我的关系
易先生对「周」以前的历史进行了推测与考证，比如女娲、三皇五帝、夏商两代。这方面算是弥补了我对中华文明史前史的空白，一步步解释了为什么到了春秋战国时期会出现百家争鸣的盛况。

在《青春志》这一部中，作者用白话讲了《左传》中的故事，描绘了2000多年以前中国人的「贵族精神」，那是一个充满理想充满血性的时代。阅读古文对我而言还是比较吃力的，好几个故事我以前听都没听过。也许将来讲给孩子听是个不错的主意。

看到《百家争鸣》，突然觉得没信仰也没什么关系，关键是自己是否有坚定的信念。「知其不可而为之」，这是孔子的信念。「要做就做大丈夫」，这是孟子的信念。「互爱互利，公平正义」，这是墨子的信念。「我的人生与你何干，要活就活得真实而自由」，这是庄子的信念。等等。借用易先生的话，「虽不能至，心向往之」啊！

总体而言，《易中天中华史》是一部读起来很轻松、又有趣味的作品。我在中学时期历史没学好，正好回顾回顾。

