#+HUGO_BASE_DIR: ../
#+SEQ_TODO: TODO DONE
#+PROPERTY: header-args :eval no
#+OPTIONS: author:nil

** DONE 我的阅读经历——从「网络文学」开始           :@阅读:阅读:经历:网络文学:
   CLOSED: [2018-12-11 Tue 02:48]
   :PROPERTIES:
  :EXPORT_FILE_NAME: my-read-experience-beginning
  :END:

** 1. 网瘾少年
 在我 10 至 13 岁这几年，因为沉迷网络游戏，偷家里的钱去泡网吧，经常被母亲教训，并多次被赶出家门。直至有一次我铁了心不再回家，身无分文离家两个月，此间辛酸不必多言。家人用尽各种办法，登电视，登报纸，贴寻人启事，最终将我找到。回去后，我痛定思痛，答应父母答应老师，一定改过自新，再也不玩网游。谁知才过一个多月，网瘾又犯。我无法控制自己，并深知对不起父母和老师，又一次离家出走。母亲已经对我彻底绝望，父亲坚持要把我找回来。我在外面处处碰壁，半个月后，父亲带着我回了家。

<!--more-->

 第二次离家，我已经没有任何颜面去面对学校里的老师和同学。我对父亲说，我不想再去学校，我也不想再念书了。父亲坚持要我继续学业，不去原来的学校没关系，书必须要念。于是，父亲陪同我坐了 30 多个小时的火车回了落后的农村老家，在老家的学校办理入学。

 回想起来，似乎从那个时候起，我的人生走向了另外一条轨道。

** 2. 农村老家
我从小在江南的一座经济飞速发展的城市里长大，父母做点小生意，四处奔波。我运气好，考进了市里最好的中学，却不争气、不懂事，成了学校里从未有过的典型。我的家乡，是一个贫困的山区，将我送回老家，实在是父亲最后的无奈之举。

家乡的秀水青山使我忘却了城市里的喧嚣，贫困的农村让我体会到了以前从未有过的一种说不出来的滋味。农村里淳朴的少年们，更是给我上了人生最宝贵的几堂课，分享，真诚，友情。我寄宿在学校，睡在 20 人一间的「危房」里，没有父母在身边，却有一番自由的欣喜。

生活总是那么的无趣，也不晓得人生有什么意义，我总想着要去做些好玩的事情。老家没有网吧，玩不了网游，我该做些什么呢？我注意到了街上的一家租书屋。

** 3. 租书屋

租书屋的老板是一个胖女人，带着一个孩子，听说是嫁到这边来的，跟村里的乡亲们也不常往来，平日没事儿就看看书，顺便把书租出去挣点生活费。我忘了我租的第一本书是什么了，也许是本黄色小说，总之从那时起就一发不可收拾。

我们那儿的农村学校的一个特点：很少有老师会去「管教」学生。大部分学生是留守儿童，书念不好的，早已自暴自弃，每日得过且过，上课打瞌睡。只要不影响正常上课秩序，至于学生在课堂上有没有认真听讲，老师通常不会多管。我也因此有了很多的时间，整日整夜的看小说。上课看，下课看，晚自习也在看，到了走火入魔的程度。

那间租书屋的书，除了大部分言情小说，其余所有的书基本都被我租过一遍。看的最多的是「网络玄幻小说」，不过就是过把瘾而已，早就没有什么印象了。印象最深的却是郭敬明的一本书。


** 4. 早期阅读兴趣
尽管说，郭敬明后来因为抄袭事件被许多人所唾弃，但他却是我阅读文学作品的生涯中，「作家链」的一个起点。我至今还记得，当时喜欢一本他写的书——《左手倒影，右手年华》，莫名其妙租来的，由此知道了郭敬明这个人。因为那本书，然后知道了安妮宝贝、村上春树。因为郭敬明，然后知道了韩寒。再后来，知道了王朔、冯唐、王小波。这几位的作品，构成了我高中时期的阅读趣味。

学校里当然也推荐过很多著名的中外作家，诸如鲁迅、老舍、沈从文、托尔斯泰、雨果、巴尔扎克等等。但是他们的作品，对那时的我而言，提不起一丁点儿兴趣。也许是年代隔得太久远了吧，完全读不下去。

从知道一位作家，然后知道另一位作家，这是非常有意思的事情，他们构成了一条我阅读顺序的「作家链」。对于我早期的阅读兴趣，就是这样机缘巧合，任凭自己的喜好，一步步培养起来的。

总有人批判，「网络文学」是「快餐文学」，是「垃圾文学」。他们不知道，有些人之所以会对文学感兴趣，或许就是从「网络文学」开始的。


