#+HUGO_BASE_DIR: ../
#+PROPERTY: header-args :eval no
#+OPTIONS: author:nil

** DONE 《易中天中华史》读后感（一）——身为中国人                      :@阅读:历史:易中天:中国历史:
   CLOSED: [2018-07-30 Mon 19:51]
   :PROPERTIES:
   :EXPORT_FILE_NAME: yizhongtian-chinese-history-1
   :END:

{{< douban 9787533938420 >}}

<!--more-->

*** 前言
#+BEGIN_QUOTE
凡读本书请先具下列诸信念： 
 
一、当信任何一国之国民，尤其是自称知识在水平线以上之国民，对其本国已往历史，应该略有所知。（否则最多只算一有知识的人，不能算一有知识的国民。）
 
二、所谓对其本国已往历史略有所知者，尤必附随一种对其本国已往历史之温情与敬意。（否则只算知道了一些外国史，不得云对本国史有知识。）

三、所谓对其本国已往历史有一种温情与敬意者，至少不会对其本国已往历史抱一种偏激的虚无主义，（即视本国已往历史为无一点有价值，亦无一处足以使彼满意。）亦至少不会感到现在我们是站在已往历史最高之顶点，（此乃一种浅薄狂妄的进化观。）而将我们当身种种罪恶与弱点，一切诿卸于古人。（此乃一种似是而非之文化自谴。）

四、当信每一国家必待其国民具备上列诸条件者比较渐多，其国家乃再有向前发展之希望。（否则其所改进，等于一个被征服国或次殖民地之改进，对其国家自身不发生关系。换言之，此种改进，无异是一种变相的文化征服，乃其文化自身之萎缩与消灭，并非其文化自身之转变与发皇。）

——钱穆《国史大纲》序言
#+END_QUOTE

以上是钱穆先生在《国史大纲》中所写的序言，同时也是我读史、对待本国已往历史的态度。自然而然，也是我阅读这本书《易中天中华史》的态度。

什么是中华文明？它是怎样形成的？它和其他文明有哪些区别，又有哪些共同的价值？它还有哪些独特的地方？它需要向其他文明借鉴什么？

这篇读后感是我读完《易中天中华史——第一部：先秦》 [fn:1] 之后的些许感想。

[fn:1] 《易中天中华史》的内容划分可以参考 [[https://zh.wikipedia.org/zh-hans/%E6%98%93%E4%B8%AD%E5%A4%A9%E4%B8%AD%E5%8D%8E%E5%8F%B2][维基百科]] 。


#+BEGIN_QUOTE
我写「中华史」，是要审视「世界文明中的中华文明」，找到「中华文明中的共同价值」，最终回答「我们是谁，从哪里来，到哪里去」这三大问题。
——卷二《国家》后记 巡航日志
#+END_QUOTE

*** 本书的特点

1. 行文通俗易懂；
2. 不仅仅只讲中华史，还讲与其他主流文明的对比；
3. 论点和推测有根据、有出处；
4. 不少令人耳目一新的观点。

这是一部既可当作消遣又能引人深思的普及历史的著作。

*** 天下主义者
在第一部中，一个有意思的观点是：中国人是「天下主义者」。

#+BEGIN_QUOTE
古人所谓「中国」，首先不是政治概念，而是文化概念，意思是「世界文化中心」。这个中心的地理条件是要在中原，因为这是古人心目中的「天下之中」。

——卷二 《国家》，第六章，闯他一回红灯，谁代表中国
#+END_QUOTE

与其他文明比较，我们民族为什么没有宗教？易中天先生认为，因为中国人是「天下主义者」。在天下主义者看来，国家不过是天下的一分子，就像大家族中的小家庭。因此，真正的人，只属于天下，不属于国家。

至少我们的祖先是这样。那些先贤「以天下为己任」，探索真理，探讨人性，探寻人生的真谛，追求更美好的社会，寻找解救世界的药方。尽管在历史的发展进程中，中华文明经历了数次分裂统一、改朝换代、外族入侵，管理制度的变革，外来文化的冲击，同时也打压不同的声音，但是，中华文明的精神内核一直延续了下来。

什么样的精神内核？

以人为本。「以祖宗代上帝，以圣人代神祇，以道德代法治，以纲常代信仰」。不信神，不信教。因此反而更开放更包容，容得下各种宗教、各种信仰、各种不同的价值观。

*** 以人为本
「以人为本」的思想是怎样产生的？

这得追溯到「周」。周从殷商手中接过了武林盟主的地位，殷商垮台的原因是「不把人当人」。在殷商时期，祭祀用「人牲」，陪葬用「人殉」，把人当器物，自然不得人心。胜利了的周，为了笼络人心，必须「把人当人」。这也就产生了最初的「以人为本」的思想。中华文明在这方面是非常「早熟」的。

从「以人为本」出发，到「以德治国」，到「以礼维持秩序，以乐保证和谐」，这是中华文明得以一直延续的解读密码。

*** 我的疑问
1. 「以人为本」的准确标准是什么？
2. 「以德治国」，通过历史我们知道，这是统治者使用的宣传手段，实际情况并非如此。如果民智渐开，这套虚假的道德主义还会管用吗？


*** 本书与我的关系
易先生对「周」以前的历史进行了推测与考证，比如女娲、三皇五帝、夏商两代。这方面算是弥补了我对中华文明史前史的空白，一步步解释了为什么到了春秋战国时期会出现百家争鸣的盛况。

在《青春志》这一部中，作者用白话讲了《左传》中的故事，描绘了2000多年以前中国人的「贵族精神」，那是一个充满理想充满血性的时代。阅读古文对我而言还是比较吃力的，好几个故事我以前听都没听过。也许将来讲给孩子听是个不错的主意。

看到《百家争鸣》，突然觉得没信仰也没什么关系，关键是自己是否有坚定的信念。「知其不可而为之」，这是孔子的信念。「要做就做大丈夫」，这是孟子的信念。「互爱互利，公平正义」，这是墨子的信念。「我的人生与你何干，要活就活得真实而自由」，这是庄子的信念。等等。借用易先生的话，「虽不能至，心向往之」啊！

总体而言，《易中天中华史》是一部读起来很轻松、又有趣味的著作。我在中学时期历史没学好，正好回顾回顾。

