#+HUGO_BASE_DIR: ../../
#+TITLE: 别了，2017！
#+DATE: 2017-12-30
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_TAGS: 总结 阅读
#+HUGO_CATEGORIES: 杂文
#+HUGO_DRAFT: false


翻阅你在这一年写的日记，「2017年6月26日：我是一个无知、无明、无趣的年轻人，对烟酒没有控制，自制力差，拖延症严重，喜欢胡思乱想，空想而缺乏行动，空有抱负却一事无成，喜好很多但一无所长。也许再过几年，我就是一个无知、无明、无趣的中年人了。」

似乎每年总有那么几天，你会感到焦虑，厌恶自己。但不管怎么说，一年又要过去了，我想从以下几个方面对你的2017年做一个总结：工作、锻炼、编程、英语、写作、阅读。

<!--more-->

** 关于工作
今年店里的营业额比去年略高了些，请注意，仅仅只是略高而已，勉强维持运转。据了解，很多生意都不好做，很多店铺在转让，经济环境不景气，这是可以理解的。但是，仍然有不少新的店铺在开张，还是有不少商家是能挣到钱的。经营不好，是你自身能力问题。

做生意涉及到，经营管理、营销推广、人际交往等等，这是一门复杂的学问，不能安于现状。要在生活与工作之间、生意与情怀之间、现实与理想之间，达到一种平衡，并不容易。多看看、多交流、多摸索，找到解决问题更好的办法。

竞争是残酷的。


** 关于锻炼
1. 站桩，要坚持下去。一是强身健体，二是锻炼正念。
2. 多组织户外活动，出门走走。今年户外活动组织的少了。
3. 每周有一个固定日子，骑行、登山、跑步都可以。走出去，走远一点。


** 关于编程
你首先得明确，编程是你的一项长期而重要的事业。保持警觉、厚积薄发，总会有开花结果的一天。过程是漫长的，不要操之过急。你在今年已经有了好的开始，但问题是，还没有一个拿得出手的实质性的产品，这是来年要认真做的事情。建议：认真对待你写的内容，把它们当做真正的产品一样去打磨。

目前可以改进的地方：
1. 熟练使用 git, gitflow
2. 写好 commit
3. 详细的 README


** 关于英语
你的英语水平有提高吗？没有。为什么？缺少刻意练习，缺少反馈。没有反馈，这是严重的问题，所以你感觉一直停留在原地。建议：做练习，这是最好的方法。


** 关于写作
你在今年重新搭建了自己的写作平台，文章数量不多，也没有多少内容，这都没有关系。千万不要被互联网上浮躁的信息流所影响，你的文字就是属于你的，真诚的表达，而非虚伪的说些假大空、附和他人的内容。把每一篇文章，都当作你的一个产品，精雕细琢，这是对读者负责的态度。

1. 在大原则不变的前提下创作
2. 对2018年的文章数量，字数，访问量做一个统计
3. 记录与分享是相辅相成的事情，多记录
4. 避免一叶障目、哗众取宠


** 关于阅读
很遗憾，由于记录的不够详细，很多看过的书、看过的内容，你都已经不记得了。今年的阅读，主要以阅读电子书为主。

下面列出印象较深的几本书：

*** 《刻意练习》《正念的奇迹》
有关提升技能、提升专注力的方法。

*** 《激荡三十年》《邓小平时代》
了解了改革开放后三十年的历史，在这期间国内的种种变化。政治变化，经济变革。

通过《激荡三十年》了解了一些企业家的崛起。

通过《邓小平时代》了解了一个伟人的崛起。其中叙述了一部分毛泽东与邓小平的恩怨，以及党内各种势力的明争暗斗。

*** 《人类简史》《未来简史》
即便对书中的部分内容不敢苟同，但有一点是可以肯定的：这两本书开拓了你对整个人类的发展宏观上的思考。
   
*** 《佛祖都说了些什么》
了解了佛教的发展与思想变迁。

*** 《月亮与六便士》
以下内容摘录自你写的日记：

#+BEGIN_QUOTE
那天在大厅里和朋友们一起喝茶，一位客人与我告别，留下了一本书赠予旅舍，供其他客人翻阅，这本书叫《月亮和六便士》。我很早就听说过这本书了，它的电子版一直躺在我的电脑硬盘里，差不多被我遗忘了。当时接过这本书，我把它放在了桌子上，第二天随手拿起来翻看，没想到一下子就被吸引了。

一口气翻完，不知怎的，我想起了在云南、西藏遇到的一些人，辞职旅行的，离家出走的，寻找生命意义的，净化心灵的，贫困潦倒的。不知道他们有没有看过这本书呢？

小说里还有个插曲，一位即将获得极好职位的实习医生，在去埃及渡假的时候，忽然觉得有冲动要在这里定居，而他也的确这样做了，放弃了他在英国即将拥有的优渥生活，一辈子在亚历山大港过着平静而贫穷的生活。很多年后，「我」遇到了当年代替这个人获得好职位的另一个医生，如今后者已经是爵士了，嘲笑前者是在「糟蹋自己」，「缺乏个性」。而「我」认为，所谓成功，衡量的标准只在每个人的内心。

生活嘛，需要六便士，也别忘了那个月亮。
#+END_QUOTE

翻到这篇日记，突然感到惭愧，哈哈！你还在被六便士苦恼着！

*** 《Principles and Practice in Second Language Acquisition》
阅读的还算顺利，理论性非常强，只是有些啰嗦，跳着看了。
几点重要方法其实很早就已经了解了。

1. 阅读原版书
2. 可理解性的输入
3. i+1 不断练习

*** 《编程人生：15位软件先驱访谈录》
如题，了解这些编程牛人的成长历程与经验分享。

*** 《JavaScript 权威指南》
通过这本书了解并入门了 JS 。

*** 《ECMAScript 6 入门》
这本书适合做参考，实际的使用，你在 codewars 上的练习中不知不觉就掌握了。

*** 《You Don't Know JS》
五星推荐的好书！讲解了 JS 这门语言中方方面面难点。英文版是开源的。


** 年度总结
「什么都略懂一点却一样也不精通」，这是我对你的评价。

回忆起这一年发生的大大小小的事情，给你几个建议：

1. 控制好自己的情绪。 
2. 好好培养两个人的感情。 
3. 少抽烟、少喝酒、少玩游戏。 
4. 多记录、多思考。

我俩已经很久没有像这次这样沟通了，用了大概一上午的时间，做了这么一个迷迷糊糊的总结。日子还是照样过，没有什么是一朝一夕就能彻底改变的。也没更多可说的了，就这样结束吧！

别了，2017！你好，2018！
